// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EstanciaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "C:\\Users\\pablo\\IdeaProjects\\ISST-20-TFG-0\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void estancia() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("roomNumber")).click();
    driver.findElement(By.id("roomNumber")).sendKeys("50");
    driver.findElement(By.id("dni")).sendKeys("00000050A");
    driver.findElement(By.id("dni")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div[2]/div/div/button/div/div/div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(2) > div > .MuiPaper-root .MuiTypography-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(2) > div > .MuiPaper-root .MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.id("hotel"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#menu-hotel > div:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(7)")).click();
    driver.findElement(By.id("hour")).click();
    driver.findElement(By.cssSelector(".MuiPickersCalendar-week:nth-child(5) > div:nth-child(4) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > .MuiButton-label > .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiPickersClock-squareMask")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPickersClock-squareMask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPickersClock-squareMask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPickersClock-squareMask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".MuiPickersClock-squareMask")).click();
    driver.findElement(By.cssSelector(".MuiPopover-root > div:nth-child(1)")).click();
    driver.findElement(By.id("nights")).sendKeys("1");
    driver.findElement(By.id("nights")).click();
    driver.findElement(By.id("nights")).sendKeys("2");
    driver.findElement(By.id("nights")).click();
    driver.findElement(By.id("nights")).sendKeys("3");
    driver.findElement(By.id("nights")).click();
    driver.findElement(By.id("nights")).sendKeys("4");
    driver.findElement(By.id("nights")).click();
    {
      WebElement element = driver.findElement(By.id("nights"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("nights")).sendKeys("5");
    driver.findElement(By.id("nights")).click();
    driver.findElement(By.id("people")).sendKeys("2");
    driver.findElement(By.id("people")).click();
    driver.findElement(By.id("comment")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("comment")).sendKeys("La mas bonita porfavor, y que la cama sea doble");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div/div/div/button/div/div/div")).click();
    driver.findElement(By.id("companyName")).click();
    driver.findElement(By.id("companyName")).sendKeys("Empresa SL");
    driver.findElement(By.id("NIF")).sendKeys("798987877");
    driver.findElement(By.id("phone")).sendKeys("132645978");
    driver.findElement(By.id("email")).sendKeys("pablo.arribas100@gmail.com");
    driver.findElement(By.id("address")).sendKeys("Calle de la Casa");
    driver.findElement(By.id("city")).sendKeys("Ciudad");
    driver.findElement(By.id("postalCode")).sendKeys("21845");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("(//button[@type=\'button\'])[4]")).click();
    vars.put("win1597", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win1597").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".MuiDialogActions-root > .MuiButtonBase-root:nth-child(1) > .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 path")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > .MuiList-root .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiExpansionPanelSummary-expandIcon .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(6) > .MuiList-root .MuiTypography-root")).click();
  }
}
