// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "C:\\Users\\pablo\\IdeaProjects\\ISST-20-TFG-0\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("roomNumber")).click();
    driver.findElement(By.id("roomNumber")).sendKeys("1");
    driver.findElement(By.id("dni")).sendKeys("00000001A");
    driver.findElement(By.id("dni")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) > .MuiList-root > .MuiButtonBase-root")).click();
    driver.findElement(By.id("roomNumber")).click();
    driver.findElement(By.id("roomNumber")).sendKeys("199");
    driver.findElement(By.id("dni")).sendKeys("00000199A");
    driver.findElement(By.id("dni")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(6) > .MuiList-root .MuiTypography-root")).click();
    driver.findElement(By.id("roomNumber")).click();
    driver.findElement(By.id("roomNumber")).sendKeys("158");
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("dni")).sendKeys("05452329H");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label")).click();
  }
}
