// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PersonalizadaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @AfterEach
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "C:\\Users\\pablo\\IdeaProjects\\ISST-20-TFG-0\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void personalizada() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("roomNumber")).click();
    driver.findElement(By.id("roomNumber")).sendKeys("30");
    driver.findElement(By.id("dni")).sendKeys("00000030A");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div[6]/div/div/button/div/div/div")).click();
    driver.findElement(By.id("customRequest")).click();
    driver.findElement(By.id("customRequest")).sendKeys("Quiero una AK-47");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > .MuiList-root .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiExpansionPanelSummary-expandIcon .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(6) .MuiButtonBase-root")).click();
  }
}
