// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ServicioHabitacionesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "C:\\Users\\pablo\\IdeaProjects\\ISST-20-TFG-0\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @BeforeEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void servicioHabitaciones() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("roomNumber")).click();
    driver.findElement(By.id("roomNumber")).sendKeys("7");
    driver.findElement(By.id("dni")).sendKeys("00000007A");
    driver.findElement(By.id("dni")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div[3]/div/div/button/div/div/div")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div/div/div/button/div/div/div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div/div/div/button/div/div/div")).click();
    {
      WebElement element = driver.findElement(By.id("element"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiMenu-list"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
    driver.findElement(By.id("comment")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("comment")).sendKeys("Olor a flores");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(2) > div > .MuiPaper-root .MuiTypography-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(2) > div > .MuiPaper-root .MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.id("element"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
    driver.findElement(By.id("comment")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("comment")).sendKeys("Sale arena");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div[3]/div/div/button/div/div/div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div[3]/div/div/button/div/div/div")).click();
    driver.findElement(By.id("panel1a-header")).click();
    driver.findElement(By.id("entrantes")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-entrantes\']/div[3]/ul/li[2]/div")).click();
    driver.findElement(By.cssSelector(".MenuSection-root-920:nth-child(2) #panel1a-header")).click();
    driver.findElement(By.id("sopas y cremas")).click();
    driver.findElement(By.xpath("//div[@id=\'menu-sopas y cremas\']/div[3]/ul/li[2]/div/div/p")).click();
    driver.findElement(By.xpath("(//div[@id=\'panel1a-header\']/div)[5]")).click();
    driver.findElement(By.xpath("(//div[@id=\'panel1a-header\']/div)[5]")).click();
    driver.findElement(By.xpath("(//div[@id=\'panel1a-header\']/div)[7]")).click();
    {
      WebElement element = driver.findElement(By.id("ensaladas"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(1) > .MuiGrid-root > .MuiGrid-root > .MuiTypography-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2) > .MuiGrid-root > .MuiGrid-root > .MuiTypography-root")).click();
    driver.findElement(By.xpath("(//div[@id=\'panel1a-header\']/div)[13]")).click();
    {
      WebElement element = driver.findElement(By.id("hamburguesas"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiGrid-spacing-xs-2 > .MuiGrid-grid-xs-true"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) > .MuiTypography-root")).click();
    driver.findElement(By.xpath("(//div[@id=\'panel1a-header\']/div)[5]")).click();
    {
      WebElement element = driver.findElement(By.id("huevos"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) > .MuiTypography-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) > .MuiTypography-root")).click();
    driver.findElement(By.id("mealElaboraremos los huevos al gusto (tortilla francesa, española, revuelto, huevos fritos con patatas)")).sendKeys("0");
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("Poco hecha");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 path")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > .MuiList-root .MuiTypography-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .MuiPaper-root > .MuiButtonBase-root .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .MuiPaper-root > .MuiButtonBase-root .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > .MuiPaper-root .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) > .MuiList-root .MuiTypography-root")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
