// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TransporteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @AfterEach
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "C:\\Users\\pablo\\IdeaProjects\\ISST-20-TFG-0\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void transporte() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("roomNumber")).click();
    driver.findElement(By.id("roomNumber")).sendKeys("20");
    driver.findElement(By.id("dni")).sendKeys("00000020A");
    driver.findElement(By.id("dni")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div[5]/div/div/button/div/div/div")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div/div/div/button/div/div/div")).click();
    {
      WebElement element = driver.findElement(By.id("way"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("hour")).click();
    driver.findElement(By.cssSelector(".MuiPickersCalendar-week:nth-child(5) > div:nth-child(4) > .MuiButtonBase-root")).click();
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".MuiPopover-root > div:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("hour")).click();
    driver.findElement(By.cssSelector(".MuiPickersDay-daySelected")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > .MuiButton-label > .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiPickersClock-squareMask")).click();
    driver.findElement(By.cssSelector(".MuiPopover-root > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    driver.findElement(By.id("hour")).click();
    driver.findElement(By.id("hour")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > .MuiButton-label > .MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPickersClock-squareMask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPickersClock-squareMask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPickersClock-squareMask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".MuiPopover-root > div:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div/div[2]/div[2]/div/div/button/div/div/div")).click();
    driver.findElement(By.id("google-map-demo")).click();
    driver.findElement(By.id("google-map-demo")).click();
    driver.findElement(By.id("google-map-demo")).sendKeys("UPM Escuela Técnica Superior de Ingenieros de Telecomunicación, Avenida Complutense, Madrid, España");
    driver.findElement(By.id("google-map-demo-option-0")).click();
    driver.findElement(By.name("destiny")).click();
    driver.findElement(By.name("destiny")).sendKeys("Google Madrid, Plaza Pablo Ruiz Picasso, Madrid, España");
    driver.findElement(By.id("google-map-demo-option-0")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.id("now"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("now")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("people")).sendKeys("2");
    driver.findElement(By.id("people")).click();
    driver.findElement(By.id("people")).sendKeys("3");
    driver.findElement(By.id("people")).click();
    {
      WebElement element = driver.findElement(By.id("people"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("people")).sendKeys("4");
    driver.findElement(By.id("people")).click();
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiDialogActions-root .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 path")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > .MuiList-root .MuiTypography-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .MuiPaper-root > .MuiButtonBase-root .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .MuiPaper-root > .MuiButtonBase-root path")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".NavigationBar-menuButton-4 .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(6) > .MuiList-root .MuiTypography-root")).click();
  }
}
